### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by yagui** [ferchaure/bci#5]
Sobre un canal que tiene mucho ruido, cuando se selecciona el ajuste automatico, tira un mensaje de error, que no genera ningun problema visible, aunque la imagen se pierde. Se adjuntan fotos.
La primera foto es la señal como se ve originalmente, la segunda foto es la misma señal ajustada a mano, y la tercera foto es lo que se ve luego de clickear en 'A' de ajustar automaticamente. De fondo en la terminal se ve el mensaje de error.
Probado con la fpga capturando ruido en una linea.
![1](https://cloud.githubusercontent.com/assets/4296015/5541618/1d6f37a2-8aba-11e4-9c62-5ddec7ae8234.png)
![2](https://cloud.githubusercontent.com/assets/4296015/5541620/20a0951a-8aba-11e4-903c-5c54a3dc53ce.png)
![3](https://cloud.githubusercontent.com/assets/4296015/5541621/22f8e0ec-8aba-11e4-826f-7cdd45fe14d1.png)

**Comment by ferchaure** [comment]
La verdad ya no recuerdo si es un problema ya solucionado. Si sigue pasando decime que versión tenes del pyqtgraph así reviso esa parte de la biblioteca, yo tengo la 0.9.10

**Comment by yagui** [comment]
Sigue sucediendo
